# Adaptation of colors from WezTerm to Alacritty in TOML format



[font]
size = 12

[font.normal]
family = "IosevkaTerm NFM"


[window]
option_as_alt = "Both"
opacity = 0.95
startup_mode = "SimpleFullscreen"
#background = "C:/Users/AngelRiera/AppData/Roaming/alacritty/skull.jpg"


[env]
TERM = "xterm-256color"

# Uncomment for Windows
#[terminal.shell]
#program = "wsl.exe"
#args = ["--cd","~", "fish" ]
